# Site settings
baseurl = "https://preview.dalafarm.com.vn/"
languageCode = "en-us"
title = "DalaFarm"
theme = "e-commerce"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-87063471-2"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "DalaFarm"
  description = "DalaFarm cung cấp các sản phẩm bột rau củ hỗ trợ bé ăn dặm dalababy, dầu tỏi, tỏi đen và các sản phẩm từ tỏi."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Trang này không thể tìm thấy"
    text = "Vui lòng trở về [trang chủ](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "DalaFarm"
    # Optional logo as brand stored in img/
#    logo = "logo.png"
    services = "Products"
    portfolio = "Sản phẩm"
    about = "Về DalaFarm"
    team = "Chúng tôi"
    contact = "Liên hệ"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
#    [[menu.postpend]]
#      url = "http://toidenducha.com"
#      name = "Đức Hà"
#      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Chào mừng bạn ghé thăm!"
    subtitle = "DalaFarm rất vui được gặp bạn"
    buttonText = "Dạo 1 vòng nào"


  # Services section
  [params.services]
    enable = false
    title = "Products"
    subtitle = ""

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-shopping-cart"
      title = "E-Commerce"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-laptop"
      title = "Responsive Design"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-lock"
      title = "Web"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Sản phẩm"
    subtitle = "Dòng sản phẩm Detox và DalaBaby của DalaFarm sẽ lên kệ trong vài ngày tới!"
    subscribleInputPlaceHolder = "Nhận email khi sản phẩm được ra mắt"
    [params.portfolio.modal]
      client = "Thương hiệu"
      category = "Giá"
      buttonText = "Đóng lại"


    # About section
  [params.about]
    enable = true
    title = "Về DalaFarm"
    subtitle = "Hành trình của chúng tôi đã bắt đầu như thế nào."
    endpoint = "Hãy đồng <br>hành cùng <br>DalaFarm!"

    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "toi-den-duc-ha.png"
      date = "June 2015"
      title = "Công ty Đức Hà được thành lập"
      description = "Ms. Hà sáng lập ra công ty Đức Hà để sản xuất và kinh doanh các sản phẩm gia vị thảo dược, nổi bật là tỏi đen cùng các sản phẩm về tỏi"

    [[params.about.events]]
      img = "dalahouse.jpg"
      date = "Feb 2016"
      title = "Công ty Dalahouse được ra đời"
      description = "Ms. Trâm sáng lập ra công ty Dalahouse với khao khát biến sản phẩm rau củ trở nên tiện lợi hơn cho những người bận rộn"

    [[params.about.events]]
      img = "dalafarm.png"
      date = "March 2017"
      title = "Câu chuyện Dalafarm bắt đầu"
      description = "Chia sẻ chung niềm đam mê về sản xuất và kinh doanh các sản phẩm Việt Nam chất lượng cao, Ms. Hà và Ms. Trâm đã hợp nhất 2 công ty Đức Hà và Dalahouse lại thành 1 công ty duy nhất mang tên DalaFarm. Cùng với 2 cộng sự khác - Ms. Thư và Mr. Vũ, chúng tôi cam kết mang những sản phẩm sạch, chất lượng cao đến với mọi người tiêu dùng!"


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Thành viên DalaFarm"
    subtitle = "Những người trẻ năng động với tham vọng lớn"
    description = "Chúng tôi là một nhóm những người trẻ đến từ các chuyên ngành khác nhau, nhưng chia sẻ chung 1 niềm đam mê lớn để mang những sản phẩm chất lượng tốt nhất của Việt Nam đến với người tiêu dùng trong và ngoài nước"

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "ha.jpg"
      name = "Lê Thị Thu Hà"
      position = "Founder"
      livesIn = "Nha Trang, Việt Nam"
      scope = [

      ]
      # For bio markdown and even multiline strings are available.
#      bio = "Sáng lập nên công ty Đức Hà, nay là một phần của DalaFarm"
      social = [
        ["fa-facebook", "https://www.facebook.com/thuha47nt"]
      ]

    [[params.team.members]]
      img = "tram.jpg"
      name = "Nguyễn Huyền Trâm"
      position = "Founder"
      livesIn = "Hồ Chí Minh, Việt Nam"
#      bio = "Sáng lập nên công ty Dalahouse, nay là một phần của DalaFarm"
      social = [
        ["fa-facebook", "https://www.facebook.com/profile.php?id=100000861713629"]
      ]

    [[params.team.members]]
      img = "thu.jpg"
      name = "Võ Thị Thanh Thư"
      position = "Co-founder"
      livesIn = "Hồ Chí Minh, Việt Nam"
#      bio = "Trùm kinh doanh, đến từ Nestle Việt Nam"
      social = [
        ["fa-facebook", "https://www.facebook.com/thanh.thuvo.1"]
      ]

    [[params.team.members]]
      img = "vu.jpg"
      name = "Lê Tấn Vũ"
      position = "Co-founder"
      livesIn = "Hồ Chí Minh, Việt Nam"
#      bio = "Kỹ sư phần mềm"
      social = [
        ["fa-facebook", "https://www.facebook.com/LeeU14"]
      ]

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      #center = true
      # Optional client title specifying the involvement
      #title = "Used and trusted by"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "envato.jpg"
        link = "#"

      [[params.clients]]
        logo = "designmodo.jpg"
        link = "#"

      [[params.clients]]
        logo = "themeforest.jpg"
        link = "#"

      [[params.clients]]
        logo = "creative-market.jpg"
        link = "#"

  # Contact section
  [params.contact]
    enable = true
    title = "Liên hệ với chúng tôi"
    subtitle  = "Hãy để lại 1 lời nhắn và chúng tôi sẽ liên lạc lại trong vòng 1 ngày."
    buttonText = "Gửi tin nhắn"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "info@dalafarm.com.vn"

    # Success and error message overwrite for async contact form
    thanks = "Xin cám ơn tin nhắn của bạn. Chúng tôi sẽ trả lời trong vòng 1 ngày."
    error = "Tin nhắn không gửi được. Vui lòng email cho chúng tôi tại info@dalafarm.com.vn"

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Tên bạn *"
      warning = "Vui lòng nhập tên."

    [params.contact.form.email]
      text = "Email của bạn *"
      warning = "Vui lòng nhập địa chỉ email."

    [params.contact.form.phone]
      text = "Số điện thoại *"
      warning = "Vui lòng nhập số điện thoại."

    [params.contact.form.message]
      text = "Lời nhắn của bạn *"
      warning = "Vui lòng nhập lời nhắn."

      # Add optional form fields to identify contact forms
      [[params.contact.form.hidden]]
        name = "DalaFarm"
        value = "dalafarm.com.vn"
      #
      [[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
        name = "site"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Bản quyền Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "https://www.facebook.com/dalafarm.com.vn/"
