# Site settings
baseurl = "http://preview.dalafarm.com.vn"
languageCode = "vi-vn"
title = "DalaFarm"
theme = "e-commerce"
defaultContentLanguage = "vi"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[[params.footer.social]]
  icon = "fa-twitter"
  link = "#"

[[params.footer.social]]
  icon = "fa-facebook"
  link = "#"

[[params.footer.social]]
  icon = "fa-linkedin"
  link = "#"
##########################################
[Languages]
#Vietnamese
[Languages.vi]
title = "DalaFarm"
weight = 0

#[[Languages.vi.menu.main]]
#url    = "/blogs"
#name   = "Blogs"
#weight = 0

[Languages.vi.params]
name = "DalaFarm"
description = "DalaFarm, provides vegetables powder and garlic related products such as tomato powder, carrot powder, garlic oil, black garlic."

# Navigation
[Languages.vi.params.navigation]
brand = "DalaFarm"
product = "Sản phẩm"
about = "Về Dalafarm"
team = "Team Dalafarm"
contact = "Liên hệ"
# Optional logo as brand stored in img/
logo = "logo.svg"

# Hero section
[Languages.vi.params.hero]
# To change the background image of the hero, replace 'header-bg.jpg' in
# the 'static/img' folder.
title = "Chào mừng đến DalaFarm!"
subtitle = "Rất vui được gặp bạn"
buttonText = "Xem sản phẩm"

# Products section
[Languages.vi.params.product]
enable = true
title = "Sản phẩm"
subtitle = "Danh mục sản phẩm của Dalafarm"
path = "san-pham"

# About section
[Languages.vi.params.about]
enable = true
title = "About"
subtitle = "How our journey started."
endpoint = "Be part<br>of our<br>story!"
path = "ve-dalafarm"

# Team section
[Languages.vi.params.team]
enable = true
# Possibility to center items
#center = true
title = "Team DalaFarm"
subtitle = ""
description = "Chúng tôi là một đội ngũ gồm những thành viên có những nền tảng khác nhau nhưng cùng 1 chí hướng để mang những sản phẩm tốt nhất của Việt Nam ra thế giới."
path = "team"

# Contact section
[Languages.vi.params.contact]
enable = true
title = "Liên hệ với DalaFarm"
subtitle  = "Để lại một tin nhắn và chúng tôi sẽ trả lời trong vòng 1 ngày."
buttonText = "Gửi tin nhắn"
thanks = "Cám ơn đã liên hệ với chúng tôi. Chúng tôi sẽ trả lời bạn trong vòng 1 ngày."
error = "Tin nhắn không gửi được. Vui lòng email cho chúng tôi qua contact@dalafarm.com"
# Since this template is static, the contact form uses www.formspree.io as a
# proxy. The form makes a POST request to their servers to send the actual
# email. Visitors can send up to a 1000 emails each month for free.
#
# What you need to do for the setup?
#
# - set your email address under 'email' below
# - upload the generated site to your server
# - send a dummy email yourself to confirm your account
# - click the confirm link in the email from www.formspree.io
# - you're done. Happy mailing!

# It is possible to substitute formspring with other providers
# as an example the mailout plugin from caddy.
# Provide the post URL for the form and depending on the provider
# add some custom JS script to finish the implementation.
# postURL = "https://example.com/mailout/"

email = "dalafarm@gmail.com"

# Success and error message overwrite for async contact form
#thanks = "Thank you for awesomely contacting us."
#error = "Message could not be send. Please contact us at mail@example.com instead."

# 'warning' defines error messages for invalid inputs
[Languages.vi.params.contact.form.name]
  text = "Tên của bạn *"
  warning = "Vui lòng nhập tên."

[Languages.vi.params.contact.form.email]
  text = "Email của bạn*"
  warning = "Vui lòng nhập email để chúng tôi có thể liên lạc lại với bạn."

[Languages.vi.params.contact.form.phone]
  text = "Số điện thoại *"
  warning = "Vui lòng nhập số điện thoại để chúng tôi có thể liên lạc lại với bạn."

[Languages.vi.params.contact.form.message]
  text = "Tin nhắn *"
  warning = "Vui lòng nhập nội dung lời nhắn."

# Footer section
[Languages.vi.params.footer]
enable = true
copyright = "Bản quyền thuộc DalaFarm (C) 2017"

[[Languages.vi.params.footer.quicklinks]]
  text = "Điều khoản sử dụng"
  link = "#"

#######################################

# English
[Languages.en]
title = "Welcome to DalaFarm"
copyright = "Copyright DalaFarm (C) 2017"
weight = 1

#[[Languages.en.menu.main]]
#url    = "/blogs"
#name   = "Blogs"
#weight = 0

#[Languages.en.params]
#  # You can use Markdown syntax for urls [text](//url.to/source) or
#  # most longer texts.
#  #
#  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
#  # for more icons. The icons are represented by their corresponding
#  # CSS class.
#
#  # To provide some metadata for search engines feel free to add a few
#  # information about you and your website.
#  name = "DalaFarm"
#  description = "DalaFarm, provides vegetables powder and garlic related products such as tomato powder, carrot powder, garlic oil, black garlic."
#  # Navigation
#  [Languages.en.params.navigation]
#    #brand = "DalaFarm"
#    # Optional logo as brand stored in img/
#    #logo = "logo.svg"
#    product = "Products"
#    about = "About"
#    team = "Team"
#    contact = "Contact"
#
#  [Languages.en.params.product]
#    enable = true
#    title = "Products"
#    subtitle = "Our product category"