# Site settings
baseurl = "http://preview.dalafarm.com.vn"
languageCode = "vi-vn"
title = "DalaFarm"
theme = "e-commerce"
defaultContentLanguage = "vi"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

##########################################
[Languages]
#Vietnamese
[Languages.vi]
title = "DalaFarm"
weight = 0

#[[Languages.vi.menu.main]]
#url    = "/blogs"
#name   = "Blogs"
#weight = 0

[Languages.vi.params]
name = "DalaFarm"
  description = "DalaFarm cung cấp các sản phẩm bột rau củ hỗ trợ bé ăn dặm dalababy, dầu tỏi, tỏi đen và các sản phẩm từ tỏi."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"
# Navigation
[Languages.vi.params.navigation]
brand = "DalaFarm"
product = "Sản phẩm"
about = "Về Dalafarm"
team = "Chúng tôi"
contact = "Liên hệ"
# Optional logo as brand stored in img/
#logo = "logo.svg"

# Hero section
[Languages.vi.params.hero]
# To change the background image of the hero, replace 'header-bg.jpg' in
# the 'static/img' folder.
    title = "Chào mừng bạn ghé thăm!"
    subtitle = "DalaFarm rất vui được gặp bạn"
    buttonText = "Dạo 1 vòng nào"

# Products section
[Languages.vi.params.product]
enable = true
title = "Sản phẩm"
subtitle = "Danh mục sản phẩm của Dalafarm"
path = "san-pham"

# About section
[Languages.vi.params.about]
enable = true
    title = "Về DalaFarm"
    subtitle = "Hành trình của chúng tôi đã bắt đầu như thế nào."
    endpoint = "Hãy đồng <br>hành cùng <br>DalaFarm!"
path = "ve-dalafarm"
    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[Languages.vi.params.about.events]]
      img = "toi-den-duc-ha.png"
      date = "June 2015"
      title = "Công ty Đức Hà được thành lập"
      description = "Ms. Hà sáng lập ra công ty Đức Hà để sản xuất và kinh doanh các sản phẩm gia vị thảo dược, nổi bật là tỏi đen cùng các sản phẩm về tỏi"

    [[Languages.vi.params.about.events]]
      img = "dalahouse.jpg"
      date = "Feb 2016"
      title = "Công ty Dalahouse được ra đời"
      description = "Ms. Trâm sáng lập ra công ty Dalahouse với khao khát biến sản phẩm rau củ trở nên tiện lợi hơn cho những người bận rộn"

    [[Languages.vi.params.about.events]]
      img = "dalafarm.png"
      date = "March 2017"
      title = "Câu chuyện Dalafarm bắt đầu"
      description = "Chia sẻ chung niềm đam mê về sản xuất và kinh doanh các sản phẩm Việt Nam chất lượng cao, Ms. Hà và Ms. Trâm đã hợp nhất 2 công ty Đức Hà và Dalahouse lại thành 1 công ty duy nhất mang tên DalaFarm. Cùng với 2 cộng sự khác - Ms. Thư và Mr. Vũ, chúng tôi cam kết mang những sản phẩm sạch, chất lượng cao đến với mọi người tiêu dùng!"

# Team section
[Languages.vi.params.team]
enable = true
# Possibility to center items
center = true
title = "Thành viên DalaFarm"
subtitle = ""
description = "Chúng tôi là một đội ngũ gồm những thành viên có những nền tảng khác nhau nhưng cùng 1 chí hướng để mang những sản phẩm tốt nhất của Việt Nam ra thế giới."
path = "chung-toi"
    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[Languages.vi.params.team.members]]
      img = "ha.jpg"
      name = "Lê Thị Thu Hà"
      position = "Founder"
      livesIn = "Nha Trang, Việt Nam"
      scope = [

      ]
      # For bio markdown and even multiline strings are available.
#      bio = "Sáng lập nên công ty Đức Hà, nay là một phần của DalaFarm"
      social = [
        ["fa-facebook", "https://www.facebook.com/thuha47nt"]
      ]

    [[Languages.vi.params.team.members]]
      img = "tram.jpg"
      name = "Nguyễn Huyền Trâm"
      position = "Founder"
      livesIn = "Hồ Chí Minh, Việt Nam"
#      bio = "Sáng lập nên công ty Dalahouse, nay là một phần của DalaFarm"
      social = [
        ["fa-facebook", "https://www.facebook.com/profile.php?id=100000861713629"]
      ]

    [[Languages.vi.params.team.members]]
      img = "thu.jpg"
      name = "Võ Thị Thanh Thư"
      position = "Co-founder"
      livesIn = "Hồ Chí Minh, Việt Nam"
#      bio = "Trùm kinh doanh, đến từ Nestle Việt Nam"
      social = [
        ["fa-facebook", "https://www.facebook.com/thanh.thuvo.1"]
      ]

    [[Languages.vi.params.team.members]]
      img = "vu.jpg"
      name = "Lê Tấn Vũ"
      position = "Co-founder"
      livesIn = "Hồ Chí Minh, Việt Nam"
#      bio = "Kỹ sư phần mềm"
      social = [
        ["fa-facebook", "https://www.facebook.com/LeeU14"]
      ]
# Contact section
[Languages.vi.params.contact]
enable = true
title = "Liên hệ với DalaFarm"
    subtitle  = "Hãy để lại 1 lời nhắn và chúng tôi sẽ liên lạc lại trong vòng 1 ngày."
    buttonText = "Gửi tin nhắn"
    thanks = "Cám ơn đã liên hệ với chúng tôi. Chúng tôi sẽ trả lời bạn trong vòng 1 ngày."
    error = "Tin nhắn không gửi được. Vui lòng email cho chúng tôi qua contact@dalafarm.com"
# Since this template is static, the contact form uses www.formspree.io as a
# proxy. The form makes a POST request to their servers to send the actual
# email. Visitors can send up to a 1000 emails each month for free.
#
# What you need to do for the setup?
#
# - set your email address under 'email' below
# - upload the generated site to your server
# - send a dummy email yourself to confirm your account
# - click the confirm link in the email from www.formspree.io
# - you're done. Happy mailing!

# It is possible to substitute formspring with other providers
# as an example the mailout plugin from caddy.
# Provide the post URL for the form and depending on the provider
# add some custom JS script to finish the implementation.
# postURL = "https://example.com/mailout/"

    email = "info@dalafarm.com.vn"

# Success and error message overwrite for async contact form
#thanks = "Thank you for awesomely contacting us."
#error = "Message could not be send. Please contact us at mail@example.com instead."

# 'warning' defines error messages for invalid inputs
[Languages.vi.params.contact.form.name]
  text = "Tên của bạn *"
  warning = "Vui lòng nhập tên."

[Languages.vi.params.contact.form.email]
  text = "Email của bạn*"
  warning = "Vui lòng nhập email để chúng tôi có thể liên lạc lại với bạn."

[Languages.vi.params.contact.form.phone]
  text = "Số điện thoại *"
  warning = "Vui lòng nhập số điện thoại để chúng tôi có thể liên lạc lại với bạn."

[Languages.vi.params.contact.form.message]
  text = "Tin nhắn *"
  warning = "Vui lòng nhập nội dung lời nhắn."

# Add optional form fields to identify contact forms
[[Languages.vi.params.contact.form.hidden]]
    name = "DalaFarm"
    value = "dalafarm.com.vn"
#
[[Languages.vi.params.contact.form.hidden]]
# Special values for name such as "page" and "site" will be autofilled
    name = "site"


# Footer section
[Languages.vi.params.footer]
enable = true
copyright = "Bản quyền thuộc DalaFarm (C) 2017"

[[Languages.vi.params.footer.quicklinks]]
  text = "Điều khoản sử dụng"
  link = "/dieu-khoan"
[[Languages.vi.params.footer.social]]
  icon = "fa-facebook"
  link = "https://www.facebook.com/dalafarm.com.vn/"

#######################################

# English
[Languages.en]
title = "Welcome to DalaFarm"
copyright = "Copyright DalaFarm (C) 2017"
weight = 1

#[[Languages.en.menu.main]]
#url    = "/blogs"
#name   = "Blogs"
#weight = 0
